<template>
<div class="container">
   <div class="row">
       <div class="col-md-12">
            <div class="no-result">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style=" display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="50" fill="none" stroke="#93dbe9" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138" transform="rotate(53.2159 50 50)">
  <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>
        <h4>جاري تحميل البيانات. <span @click="reloadPage()">اتفرج اون لاين</span></h4>
    </div>
       </div>
   </div>
</div>
</template>
<script>
export default {
    methods: {
  reloadPage(){
    window.location.reload()
  }
}
}
</script>
<style lang="scss" scoped>
@import '~/assets/sass/_vars.scss';
@import '~/assets/sass/_mixins.scss';
.no-result{
    text-align:center;
    background-color: $primary-color;
    color:#fff;
    padding: 0.5rem 4rem;
    border-radius: 10px;
    margin: 1rem auto;
    span{
        color:$secondary-color;
        text-decoration: none;
        cursor:pointer;
    }
    svg{
        height: 30px;
        margin: 1rem auto;
        background-color: transparent;
    }
}
.darkMod{
  .no-result{
    text-align: center;
    background-color: #63636317;
    color: #fff;
    padding: 0.5rem 4rem;
    border-radius: 5px;
    margin: 1rem auto;
  }
}
</style>